# Generated by Django 4.1.1 on 2022-10-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaMahasiswa', models.CharField(max_length=40)),
                ('NIM', models.CharField(max_length=40)),
                ('TTL', models.CharField(max_length=40)),
                ('Photo', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=40)),
                ('Fakultas', models.CharField(max_length=40)),
                ('Prodi', models.CharField(max_length=40)),
                ('Alamat', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaTendik', models.CharField(max_length=40)),
                ('NIP', models.CharField(max_length=40)),
                ('TTL', models.CharField(max_length=40)),
                ('Photo', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=40)),
                ('Fakultas', models.CharField(max_length=40)),
                ('Prodi', models.CharField(max_length=40)),
                ('Alamat', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='dosen',
            old_name='Nama',
            new_name='NamaDosen',
        ),
    ]
