# Generated by Django 4.1.1 on 2022-10-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0002_mahasiswa_tendik_rename_nama_dosen_namadosen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='NamaDosen',
            new_name='Nama',
        ),
    ]
