# Generated by Django 4.1.1 on 2022-10-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0004_dosenfaperta_dosenfeb_dosenfh_dosenfisip_dosenfk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosenfaperta',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dosenfeb',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dosenfh',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dosenfisip',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dosenfk',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dosenfkip',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dosenft',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dosenpascasarjana',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswafaperta',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswafeb',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswafh',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswafisip',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswafk',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswaft',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswapascasarjana',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stafffaperta',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stafffeb',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stafffh',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stafffisip',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stafffk',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stafffkip',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='staffft',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='staffpascasarjana',
            name='nomor',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
