# Generated by Django 4.1.1 on 2022-10-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0006_remove_dosenfaperta_nomor_remove_dosenfeb_nomor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkreditasiFkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(max_length=50)),
            ],
        ),
    ]
