# Generated by Django 4.1.1 on 2022-10-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0007_akreditasifkip'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMJFkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
    ]
