# Generated by Django 4.1.1 on 2022-10-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultas', '0008_hmjfkip'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuanganFkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=300, null=True)),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
    ]
